language: go
go:
  - 1.13.x
os:
  - linux
dist: trusty
sudo: false
install: true

env:
  - GO111MODULE=on

before_script:
  - sudo apt-get -y -q install upx
  - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
  - export PATH=$PATH:/$(pwd)/bin

script:
  - go build
  - go test ./... -cover
  - goreleaser --snapshot --skip-publish
