language: go
go:
  - 1.13.x
os:
  - linux
dist: trusty
sudo: false
install: true

env:
  - GO111MODULE=on

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

script:
  - go build
  - go test ./... -cover
  - ./bin/goreleaser --snapshot --skip-publish --rm-dist
